[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.install]
cmds = ["dotnet restore backend/RenovoWorkshop.sln"]

[phases.build]
cmds = ["dotnet publish backend/RenovoWorkshop.Api/RenovoWorkshop.Api.csproj -c Release -r linux-x64 --self-contained true -o /app/out"]

[start]
cmd = "/app/out/RenovoWorkshop.Api"
